project:
  type: website
  output-dir: docs

website:
  title: "Camila Cedano | Data & Policy Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/milacedano
      - icon: linkedin
        href: https://www.linkedin.com/in/maria-camila-cedano/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

