project:
  type: website
  output-dir: docs
  
execute:
  warning: false
  message: false

website:
  title: "Maria Camila Cedano"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/milacedano
      - icon: linkedin
        href: https://www.linkedin.com/in/maria-camila-cedano/

format:
  html:
    theme: flatly
    css: styles.css
    title-block-banner: false

editor: visual
